CREATE ROLE sql_agent WITH LOGIN PASSWORD 'master_01';
GRANT CONNECT ON DATABASE pagila TO sql_agent;
GRANT USAGE ON SCHEMA public TO sql_agent;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO sql_agent;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO sql_agent;
